### ISSUE TITLE
Writing multifile topology fails to parse path

### ISSUE THREAD

**Issue by bertadenes** [deGrootLab/pmx#14]
I am using the develop branch.
I have a system of three protein chains, thus by default, `topol.top` refers to three `.itp` files for each chain. pmx reads them correcly, but tries to write the `.itp` files nested, due to line 154 of `src/pmx/scriptsgenerate_hybrid_topology.py`:
`
out_fn = '{0}/pmx_{1}'.format(basepath,itp_fn)
`
This obviously throws an error.
Line 147 goes like this:
`
    basepath = outfile.rsplit('/',1)[0]
`
for now, my workaround was to change that to
`
    basepath = os.path.dirname(os.path.abspath(outfile))
`
so at least all files are written, but due to the str representation of the topol object and link 154, it writes files such: `pmx_topol_Protein_chain_A.itp`. I can rename them and work on.
However, I am not entirely sure I understood the intended behaviour. Perhaps I could only work on the `itp` which has the mutation, but in general, there can be more than one. Either way, I suggest a fix and a revision to that piece of code, even if more comprehensive exception handling is not affordable at the moment.

**Comment by vgapsys** [comment]
Thanks for reporting this. I have now fixed the basepath for .itp files.

The files are written as "pmx_original_itp_name.itp" in order not to overwrite the original itp files. Also, a new topology (.top) file is generated which refers to the newly created "pmx_original_itp_name.itp" files. This .top file should be used for the further simulations.

Does this resolve the issue?

**Comment by bertadenes** [comment]
Correct, I realized the names are consistent with the new topology file. It did work, yes, I have since run a few simulations using the hybrid topology.
I may have some enhancement suggestions later, if I find the time to compile them. Thanks for the nice tool.

**Comment by vgapsys** [comment]
Great to hear it works now. Let me know of the further suggestions. Will close this issue now.
