### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by biotech70** [deGrootLab/pmx#22]
Hi. during work with pmx get the below error, how can I resolve it?
![error](https://user-images.githubusercontent.com/73783725/140735761-1e74b233-594a-4717-b51d-b49bc4800951.png)

**Comment by vgapsys** [comment]
Does the protein structure contain all atoms and are they in accord with the Gromacs atom naming?
I would suggest running the structure through "gmx pdb2gmx" before bringing it to pmx.

**Comment by biotech70** [comment]
Thanks so much,  the problem was solved using pdb2gmx.
