### ISSUE TITLE
Using pmx with parmed generated gromacs topologies

### ISSUE THREAD

**Issue by aminsagar** [deGrootLab/pmx#30]
Dear PMX developers,
I am trying to setup FEP calculations for a protein-peptide system where the peptide has some non-natural amino acids which I have parameterized using Antechamber with gaff2. My workflow is as follows.

1) Use antechamber to parameterize non-natural amino acids.
2) Use tleap to generated Amber format topologies of the complex using ff14SB force field.
3) Use Parmed to convert Amber format topologies to Gromacs format.
4) Run simulations using gromacs.

My question is that if I generate gromacs systems for both WT and mutant using the above protocol, can I use pmx to generate hybrid topologies and run FEP simulations?

**Comment by vgapsys** [comment]
Hey,

for that you would need to generate entries in .rtp and .mtp files for the mutated residue: "pmx genlib" will do that. Afterwards, you can treat the hybrid residue as a regular amino acid mutation and set up the free energy calculations.

**Comment by aminsagar** [comment]
Thanks for your response. I think I should give more details to explain the situation.

I am studying a protein-peptide complex, where the peptide has a fluoroglutamine. 
I am interested in mutating a Lysine to Alanine in the peptide and study the effect using FEP.
I generated gaff parameters for fluoroglutamine using ambertools and used those to generate the prmtop and rst files for the complexes (WT and K2A).
Then, I used parmed to convert the amber prmtop and rst files to gromacs topology (top) and coordinate (gro) files.
So, now I have 4 files which are enough to run the simulations with gromacs. These are WT.top, WT.gro, K2A.top and K2A.gro.
I read the documentation of genlib and it seems I have to give the path to the forcefield files. I don't have such a folder with forcefield files, but all the information is contained in these .top files.
Is there a way to read in top files instead and write the hybrid topology files to run FEP simulations with gromacs?

Thanks.
Amin.

**Comment by vgapsys** [comment]
I assume that by K2A.top you mean a plain topology file where alanine is simply replacing lysine, i.e. this is not a hybrid residue containing topology? If so, you need to take several steps back and incorporate your fluoroglutamine into gromacs topology database (convert the .top entry to .rtp entry and add it to the aminoacids.rtp). Next, use the standard pmx procedure to create hybrid protein structure/topology files for the hybrid residue K2A: https://link.springer.com/protocol/10.1007/978-1-4939-8736-8_2

Vytas

**Comment by aminsagar** [comment]
Thanks. I will do the conversion from frcmod/mol2 to itp and give it a try.
