### ISSUE TITLE
Gromacs 4.6 with an alternative soft-core function

### ISSUE THREAD

**Issue by noahharrison64** [deGrootLab/pmx#31]
Hi,

I'm looking at setting up non-equilibrium FEP calculations and have settled on PMX as a toolkit and parameter file repository to do this. In the PL benchmarking directory I saw in the readme the following line:

> These files are meant to be used with a custom gmx4.6 version with an alternative soft-core formulation: 
pmx.mpibpc.mpg.de/gromacs462_newsc.tar
and on the pmx website
> Using the default Gromacs soft-core may cause artifacts during the non-equilibrium transitions. We have implemented an alternative soft-core version into Gromacs 4.6.2 version (unfortunately GPU support here is not yet supported with the free energy calculations): [gromacs462_newsc.tar](http://pmx.mpibpc.mpg.de/gromacs462_newsc.tar) The default soft-core parameters in this Gromacs version are hardcoded following the original publication: [DOI: 10.1021/ct300220p](http://pubs.acs.org/doi/abs/10.1021/ct300220p)

So I have a few questions surrounding this modified potential:

1. Are they still required in this format, or is there another way to specify them/are there any work arounds that allow running the latest version of GMX?
2. Due to the lack of GPU  support in this package, if given the option I'd like to run this version of gromacs only for the transitions, so the bulky equilibrium end state simulations can receive GPU support. Is this possible/is mixing GMX versions in this manner okay/appropriate?

Many thanks,
Noah

**Comment by zetadin** [comment]
Hi, Noah.

The new soft core functions are available as part of the gmx 2022 and newer ([release notes link](https://github.com/gromacs/gromacs/blob/bd791c7cba317d8d59c86c2edcc923d6263f8d0a/docs/release-notes/2022/major/features.rst#a-new-formulation-of-soft-core-interactions-for-free-energy-calculations)), so no workaround is necessary. It is used by setting `sc-function=gapsys` in the mdp file. I am not sure if GPU support for the soft-core interactions is present or not (@vgapsys may know better), but the rest of the nonbonded interactions are still offloaded to the GPU with this setting. And I don't see a performance drop between using the old and the new soft-core functions.

Cheers, Yuriy.

**Comment by noahharrison64** [comment]
Hi Yuriy,

Thanks for the reply - good to know, that's incredibly helpful!

Cheers,
Noah

**Comment by noahharrison64** [comment]
Hi Yuriy,

Just had a look at the TI mdp files I'm going to be using. They are obtained from the[ prot_lig_benchmark section](https://github.com/deGrootLab/pmx/blob/master/protLig_benchmark/mdp/ti_l0_gmx2018.mdp) of this repo. 

In the mdp they have the following SC parameters assigned:

` Free energy control stuff
free-energy              = yes
init-lambda              = 0
delta-lambda             = 4e-5
sc-alpha                 = 0.3
sc-sigma                 = 0.25
sc-power                 = 1
sc-coul = yes
;alpha_Q = 0.3
;sigma_Q = 1.0

refcoord-scaling = com
`

I'm wondering, since these MDP files were created for GMX 2018, do I need to replace any of these parameters if I include the sc-function=gapsys line?  According to the [gromac mdp docs](https://manual.gromacs.org/documentation/current/user-guide/mdp-options.html) the sc-parameters are only relevant to the Beutler soft-core scheme, so I would assume I should add sc-function=gapsys and then remove 
`sc-alpha                 = 0.3
sc-sigma                 = 0.25
sc-power                 = 1
sc-coul = yes`

Is this correct? And should I remove alpha-Q or sigma-Q assignments

**Comment by zetadin** [comment]
Hi, Noah.

No need to remove them. They will just be ignored if you set `sc-function=gapsys`. Instead `sc-gapsys-scale-linpoint-lj = 0.85   sc-gapsys-scale-linpoint-q=0.3   sc-gapsys-sigma-lj=0.3` will be used. If you don't specify them, gmx grompp will use these defaults, which seem to match the 2012 paper. You can see them appearing in mdout.mdp even if you don't specify them.

Cheers,
Yuriy.

**Comment by noahharrison64** [comment]
Okay fantastic, thanks for clarifying.

Cheers,
Noah

**Comment by noahharrison64** [comment]
Hi Yuriy,

I ended up not using the sc-function=gapsys flag since I'm running gromacs 2021 which doesn't appear to have it included.
When running end state equilibrations (init lamda is stable at either 0 or 1) I get a warning from having sc-alpha=0.3 set in the mdp file. 

> WARNING 2 [file /root/et/et/fep/mdps/eq_nvt_a.mdp, line 240]:
  You are using soft-core interactions while the Van der Waals interactions
  are not decoupled (note that the sc-coul option is only active when using
  lambda states). Although this will not lead to errors, you will need much
  more sampling than without soft-core interactions. Consider using
  sc-alpha=0.

Should sc-alpha not be set to 0 during the equilibration stages, rather than it's current value of 0.3? 

Thanks,
Noah

**Comment by vgapsys** [comment]
Hey Noah,

it is safe to ignore the warning.

Vytas

**Comment by noahharrison64** [comment]
Ok excellent - thank you Vytas.
